project_id = "qmprswbgkpzcvexmmcbf"

[functions.roomsonline-pms-api]
verify_jwt = true

[functions.benson-api]
verify_jwt = true

[functions.checkfront-api]
verify_jwt = true

[functions.create-user]
verify_jwt = true

[functions.push-booking]
verify_jwt = true

[functions.reset-user-password]
verify_jwt = true

[functions.sync-rates-availability]
verify_jwt = true

[functions.dashboard-insights]
verify_jwt = true

[functions.send-access-request]
verify_jwt = false

[functions.send-booking-email]
verify_jwt = true

[functions.tripadvisor-api]
verify_jwt = false
